disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Yanis E.B"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "1 January 2001"

[[params.author.links]]
email = "mailto:yanis.elbeilk@proton.me"

[[params.author.links]]
github = "https://github.com/yaniselbeilk"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/yaniselbeilk/"

[[params.author.links]]
mastodon = "https://fosstodon.org/@yanislblk"

["params.author"]
name = "Yanis EL BEILK"
email = "yanis.elbeilk@proton.me"
image = "/img/profile.jpg"
headline = "SysOps/DevOps Engineer"
bio = "Passionate about technology, sports, music and video games in my spare time"
