disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1
title = "Yanis E.B"

[params]
displayName = "Français"
isoCode = "fr"
rtl = false
dateFormat = "1 January 2001"

[[params.author.links]]
email = "mailto:yanis.elbeilk@proton.me"

[[params.author.links]]
github = "https://github.com/yaniselbeilk"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/yaniselbeilk/"

[[params.author.links]]
mastodon = "https://fosstodon.org/@yanislblk"

["params.author"]
name = "Yanis EL BEILK"
email = "yanis.elbeilk@proton.me"
image = "/img/profile.jpg"
headline = "Ingénieur SysOps/DevOps"
bio = "Passionné de technologie, de sport, de musique et de jeux vidéo à mes heures perdues"
