[[main]]
name = "About"
pageRef = "/about"
identifier = "GyOmlLz7uj"
weight = 2

[[main]]
name = "Resume"
pageRef = "/resume"
identifier = "VjWe9y1hUY"
weight = 3

[[main]]
name = "Home"
pageRef = "/"
identifier = "yozmQu8OIa"
weight = 1
