[[main]]
name = "À propos"
pageRef = "/about"
identifier = "GyOmlLz7uj"
weight = 2

[[main]]
name = "CV"
pageRef = "/resume"
identifier = "VjWe9y1hUY"
weight = 3

[[main]]
name = "Accueil"
pageRef = "/"
identifier = "yozmQu8OIa"
weight = 1
